### ISSUE TITLE
package sophus not found error

### ISSUE THREAD

**Issue by ajay1606** [tier4/YabLoc#43]
Hello, 
Awesome and must needed in Autoware. Much awaited module, thank you so much for sharing very useful repository.

We are very interested in testing this module, but unfortunately there is build error stating **Sophus** missing.

```
** WARNING ** io features related to pcap will be disabled
CMake Error at CMakeLists.txt:29 (find_package):
  By not providing "FindSophus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Sophus", but
  CMake did not find one.

  Could not find a package configuration file provided by "Sophus" with any
  of the following names:

    SophusConfig.cmake
    sophus-config.cmake

  Add the installation prefix of "Sophus" to CMAKE_PREFIX_PATH or set
  "Sophus_DIR" to a directory containing one of the above files.  If "Sophus"
  provides a separate development package or SDK, be sure it has been
  installed.

```
After looking for **Sophus** library, i realized that currently **Sophus** library not supported for ROS2-Humble.
https://robostack.github.io/humble.html

![image](https://github.com/tier4/YabLoc/assets/29722843/3c789e15-18f4-4d51-8546-a98340ec7139)

Would you please let us know how to install above  library to test this localization module in ROS2-Humble ?

**Comment by rsasaki0109** [comment]
Can't you install Sophus with "sudo apt install ros-humble-sophus"? Instead, it might be better to run "rosdep install --from-paths src --ignore-src -r -y" in the workspace.

**Comment by KYabuuchi** [comment]
As rsasaki0109 has pointed out, Sophus should be installed with one of those commands.
* `sudo apt install ros-humble-sophus` 
* `rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO`


I'm not familiar with RoboStack, but isn't that page a list of packages offered by RoboStack via the Conda package manager?
We can check [https://github.com/ros/rosdistro](https://github.com/ros/rosdistro/blob/0abaf8f1be6a04ace05f8bb845c198b839bac6b8/humble/distribution.yaml#L6584-L6598) to see if the package can be installed with apt or rosdep.

**Comment by ajay1606** [comment]
@rsasaki0109 @KYabuuchi Thank you so much for your feedback and its installed successfully after running rosdep.

And confirmed all dependency installed 
`rosdep install --from-paths src --ignore-src -r -y`
`#All required rosdeps installed successfully`

But again following error raised for library `glog`

```
CMake Error at CMakeLists.txt:25 (find_package):
  By not providing "Findglog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glog", but
  CMake did not find one.

  Could not find a package configuration file provided by "glog" with any of
  the following names:

    glogConfig.cmake
    glog-config.cmake

  Add the installation prefix of "glog" to CMAKE_PREFIX_PATH or set
  "glog_DIR" to a directory containing one of the above files.  If "glog"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Would you please help me fix this issue aswell !

**Comment by KYabuuchi** [comment]
@ajay1606  Sorry. It is my fault.  I will update the README later.
Thanks for your interest in yabloc. :+1:
